//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOdasi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilanlar
    {
        public int İlanId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SehirId { get; set; }
        public Nullable<int> BransId { get; set; }
        public Nullable<int> SinifId { get; set; }
        public Nullable<int> IlanRole { get; set; }
        public Nullable<System.DateTime> IlanTarih { get; set; }
        public Nullable<decimal> minUcret { get; set; }
        public Nullable<decimal> maxUcret { get; set; }
    
        public virtual Branslar Branslar { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual Siniflar Siniflar { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
